name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright-run:
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.1-jammy
    strategy:
      matrix:
        node-version: [22, 24]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests (Chrome only)
      env:
          BASE_URL: ${{ secrets.BASE_URL }}
          HTTP_CREDENTIALS_USERNAME: ${{ secrets.HTTP_CREDENTIALS_USERNAME }}
          HTTP_CREDENTIALS_PASSWORD: ${{ secrets.HTTP_CREDENTIALS_PASSWORD }}
      run: npx playwright test tests/hw_29/test_29_2.spec.js  --project=chromium
    - name: Upload Playwright Report artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: playwright-report-${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 7
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          junit-report/*.xml
          junit-report/*.json
    - name: Deploy on pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./monocart-report-ui